env: prod
version: v1.0
address: 0.0.0.0:80
cron_enable: true

plugs:
  address: 0.0.0.0:6060
  #prometheus
  prom:
    enable: true
    path: /prom/metrics


logs:
  level: info
  path: logs
  stdout: true
  maxsize: 100
  maxBackups: 10
  maxAge: 1
  compress: true