env: test
version: v1.0
address: "0.0.0.0:80"
cron_enable: true
#prometheus
prom:
  enable: true
  address: 2112
pprof:
  enable: true
  address: 6060
logs:
  level: info
  path: logs
  stdout: true
  maxsize: 100
  maxBackups: 10
  maxAge: 1
  compress: true